version: "3.9"
services:
  prisma-db:
    container_name: go-ride-coding-test-db
    image: postgres:15
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: go-ride-coding-test
    volumes:
      - prisma-store:/var/lib/postgresql/go-ride-coding-test

volumes:
  prisma-store:
    driver: local